# Generated by Django 3.0.8 on 2020-07-12 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocService', '0002_auto_20200712_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='get_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='reg_person',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='regist_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
