# Generated by Django 3.0.8 on 2020-07-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocService', '0003_auto_20200712_2242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='doc_file',
            field=models.FileField(blank=True, upload_to='uploads/<django.db.models.fields.AutoField>'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reg_number',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
