# Generated by Django 3.0.8 on 2020-07-12 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocService', '0004_auto_20200713_0005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='get_date',
            field=models.CharField(max_length=30),
        ),
    ]
