# Generated by Django 3.0.8 on 2020-07-12 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocService', '0005_auto_20200713_0007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='regist_date',
            field=models.CharField(blank=True, default='07/13/2020', max_length=20, null=True),
        ),
    ]
