# Generated by Django 3.0.8 on 2020-07-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DocService', '0006_auto_20200713_0017'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='track_number',
            field=models.CharField(default=1234, max_length=100),
            preserve_default=False,
        ),
    ]
